### ISSUE TITLE
New Feature request texmf.cnf lookup file

### ISSUE THREAD

**Issue by alastairgott** [therion/therion#160]
I was wondering if it would be possible to create a lookup file for the texmf.cnf to look to within the Therion program files, perhaps in a user file.

so instead of being:
TEXINPUTS = $TEXMF/tex;.
MPINPUTS = .

It could perhaps be:
TEXINPUTS = $Therion/User;$TEXMF/tex;.
MPINPUTS = $Therion/User;.

If you could also save the Absolute path to a file (into the user file) from the Thconfig much like selecting a background image in th2. this could make therion more user friendly & portable? As the separately shared root to the image or metapost could be saved as user data and used across various projects (images could be pulled in from an absolute path to a dropbox/onedrive/Googledrive set of shared files)

![Therionmod Texinputs](https://user-images.githubusercontent.com/16326426/69746284-d4411880-113b-11ea-8d9b-c336852d4e56.png)

**Comment by mbudaj** [comment]
As I understand from the discussion [here](https://mailman.speleo.sk/pipermail/therion/2019-November/007979.html), the aim is to support relative include paths. This has been implemented since f9d2f937c0e18353e167a69f376ae73d03ca3de3 without the need to modify texmf.cnf; see \inputrel, \savepath and \loadpicture in TeX and inputrel() in MetaPost.
