### ISSUE TITLE
difficulties to shift a lower gallery

### ISSUE THREAD

**Issue by rsmartinelli** [therion/therion#249]
someone can help me with this issue? I´m a frequent user of Therion, I have made a lot of maps, but now I´am having some difficulties to dislocate a lower gallery. 

I´m doing......
________________________________________________
map map1 
nivel1
conection
seca
endmap

map map2 
break
nivel2 
break
endmap

map tudo 
map2 [40 60 m] below
map1 
endmap

endsurvey
_____________________________________________________________

**Comment by CaverBruce** [comment]
In my experience, having a break with no object before or after it will cause a crash.

I think your map2 contains a problem definition.

Bruce

**Comment by rsmartinelli** [comment]
Hy Bruce, thank you for your quick response.
I know about the "break" problem, I put that there because I don't know what to do more, I have tried everything, but the "map2" doesn´t move. Have a look in the full "th".



survey Matadero -title "Caverna do Matadero"
import topo/Matadero.3d -surveys use -cs utm22s

#**** aqui vc vai colocar os arquivos th2***
input nivel1.th2

#expedição 2017
input gal_seca.th2
input nivel2.th2



#Junções 2017
join sec_1:end 1702_1:0
join sec_2:0 1702_2:0
join 1702_3:end  inf_1:end
join 1702_2:end  inf_2:0
join cone_1:end sup_1:end
join sup_2:end cone_2:0

#**** Criacao dos Mapas  ****
map map1 
scrap1
conection
seca
endmap

map map2 
scrap_rio
conex 
endmap

map tudo 
map2 [40 60 m] below
break
map1 
endmap

endsurvey


If you don't mind, I can send to you the project.

Best regards from Brazil!

**Comment by CaverBruce** [comment]
Yes

Happy to have a look.

I’m always interested to see how people use Therion, and maybe solve some problems as well.

Bruce

**Comment by rsmartinelli** [comment]
[https://www.dropbox.com/s/brhb1ftc3homl2j/Caverna%20Nova%20%28Matadero%29.rar?dl=0](url)

Hy Bruce, Thanks for your kindness.

Like I said, I´m having trying to fix this problem for a long time, I made a lot of caves more complex that this one, but I can´t move the "map2".

One more time, thank you for your time.

**Comment by CaverBruce** [comment]
The reason that your map definition was not honoured is because you did not select the map (or any map) for output.
Therefore only the scraps were output, and the map definitions were not used.
The solution here.
![image](https://user-images.githubusercontent.com/19825868/85835195-b7131c00-b7e8-11ea-9d50-d1e8c3890560.png)

There was also a missing quote character after granito, but that did not seem to worry Therion for some reason.

Have you subscribed to the Therion discussion forum?
https://therion.speleo.sk/contact.php

I think there are many more people there to help resolve problems like this one.

Your map drawing is very detailed.  I will study it to see how you have managed the cross sections.

**Comment by rsmartinelli** [comment]
hello Bruce! 

Very,  very, very thaks!

 I know that was a simple solition, but when you look and doesnt see the obvius, its a reliefe to see the solution.

I made my signature in the therio list and i will make a poust about this conversation.

Thank you again!

Ricardo Martinelli


Enviado do meu iPhone
