### ISSUE TITLE
ithems color settings

### ISSUE THREAD

**Issue by matls** [therion/therion#408]
It is possible change color setting range from actual 0-100 to standard RGB 0-255? Or add some color map/calculator into x therion? Now it's not so easily find the right color. Maybe I miss something?

**Comment by ladislavb** [comment]
There are online colour calculators available - for example: https://www.tydac.ch/color/ (see RGB FME) or there is Excel spreadsheet from Bruce Mutton available on wiki pages helping with such conversions - https://therion.speleo.sk/wiki/_media/tips:rgb_to_therion_colour_mapping.xls

**Comment by smudrak** [comment]
I have tried to add support for CSS color notation to therion. Would it help? You may try it in the latest commit (4d8e987).
Specification `color map-fg [#aa0000]` should now work (and all other color specifications). The only problem is, that `#` character is used for comments in therion, therefore `[]` brackets or `""` are needed. May be, some alternative character like `@` instead of / in addition to `#` would be better.

**Comment by ladislavb** [comment]
@smudrak What about some syntax like hex(ff0000) or html(ff0000)? Similary to that we could maybe also support rgb(255,0,0) syntax. For programmers it might be also understandable to use '#ff0000' = a string enclosed in single quotes. But as you said, I would be very careful with the # character usage outside of comments. It could lead to many unexpected problems.

**Comment by smudrak** [comment]
We have simplified it a little bit more - in the latest commit, hex color RGB spec is without any special characters - e.g. `color map-fg ffeeaa`. If it will not be enough, we may add rgb(255,0,0) support in the future.
