### ISSUE TITLE
Text for survey teams and explo teams limited to one space

### ISSUE THREAD

**Issue by Bergil006** [therion/therion#441]
The text in survey centerline blocs for team and explo-team is limited with only 1 space.
You can write
centerline
     team "ABC DEF"
     explo-team "John Timer"

But you can't
centerline
     team "ABC DEF GHI"
     explo-team "John Timer Second"

Can it be possible to let the label of the people (or team) name have more than 1 space character ?
Thanks

**Comment by CaverBruce** [comment]
Have a look at https://therion.speleo.sk/wiki/drawingchecklist#scrap

Where you need to enter a 'person' data type, such as 'author' (or survey 'team' or 'explo-team' member for surveys) Therion assumes a person has two words in their name (first name and last name). If you enter more than two words, Therion will report an error unless you use a forward slash, /, in place of ONE of the spaces....

More on the web page

**Comment by rursprung** [comment]
> Therion assumes a person has two words in their name (first name and last name).

see point 5 in the list of [Falsehoods Programmers Believe About Names](https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/) 😞

is there a good reason why this limitation exists?

**Comment by CaverBruce** [comment]
Ahh, I worded my comment poorly.  I don't think it is a limitation.  There may be a limit on the number of words in a person's name, but (without trying to verify beyond four words) I expect it is reasonably large.
By default Therion assumes firstname lastname, and if you want more than that, the user must use forward slash / (most likely to control which word the name is sorted by and to ensure more than two words per name is intentional - my speculation).  
https://therion.speleo.sk/wiki/drawingchecklist#scrap explains further.

**Comment by mbudaj** [comment]
As explained by Bruce, there is actually no limitation. Just use the slash character to separate the surname(s) and the other name(s).
