### ISSUE TITLE
Xtherion PNG On Mac

### ISSUE THREAD

**Issue by kmichael500** [therion/therion#479]
In order to open PNGs you have to enable all file types in the file selector since Xtherion doesn't think it's a valid file type.

This is only a bug on Mac.

**Comment by IdlePhysicist** [comment]
I will open with a question – _do JPEGs exhibit the same behaviour?_  I would assume that they do based on the following.

The valid image file types are set here [1] where we look to see if the `Img` package can be loaded, and based on whether that package if available we will add PNG & JPEG related extensions to the recognised file types map.

Given that you can select the PNG file manually and I am assuming that the world doesn't end i.e. XTherion crashes that we don't actually need the check for the `Img` package.  Though maybe I have this incorrect?

[1] https://github.com/therion/therion/blob/master/xtherion/init.tcl#L30-L42

---

This part below may not be of interest.

I believe this is only a bug on Macs because at least on my MacBook the `Img` package is not installed (by default – I assume).   On my Debian Linux server I can load the `Img` package, I assume that it _is_ installed by default / bundled with TCL.  `Img` is in the `libtk-img` package on Debian [2].

You can test this by running this in your terminal.

```
tclsh
package require Img
```

[2] https://wiki.tcl-lang.org/page/Img
